version: '3.8'

services:
  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:6.2-alpine
    container_name: ecommerce-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Authentication service
  authentication-service:
    build:
      context: ./server/authentication-service
      dockerfile: Dockerfile
    container_name: ecommerce-auth-service
    environment:
      - PORT=${AUTHENTICATION_SERVICE_PORT}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - ecommerce-network

  # Common data service
  common-data-service:
    build:
      context: ./server/common-data-service
      dockerfile: Dockerfile
    container_name: ecommerce-common-data-service
    environment:
      - PORT=${COMMON_DATA_SERVICE_PORT}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${COMMON_DATA_SERVICE_PORT}:${COMMON_DATA_SERVICE_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce-network

  # Search suggestion service
  search-suggestion-service:
    build:
      context: ./server/search-suggestion-service
      dockerfile: Dockerfile
    container_name: ecommerce-search-suggestion-service
    environment:
      - PORT=${SEARCH_SUGGESTION_SERVICE_PORT}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - COMMON_DATA_SERVICE_PORT=${COMMON_DATA_SERVICE_PORT}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "${SEARCH_SUGGESTION_SERVICE_PORT}:${SEARCH_SUGGESTION_SERVICE_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce-network

  # Payment service
  payment-service:
    build:
      context: ./server/payment-service
      dockerfile: Dockerfile
    container_name: ecommerce-payment-service
    environment:
      - PORT=${PAYMENT_SERVICE_PORT}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ecommerce-network

  # Frontend React
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "${REACT_APP_PORT}:80"
    environment:
      - NODE_ENV=${REACT_APP_ENVIRONMENT}
      - REACT_APP_AUTHENTICATION_SERVICE_URL=http://authentication-service:${AUTHENTICATION_SERVICE_PORT}
      - REACT_APP_COMMON_DATA_SERVICE_URL=http://common-data-service:${COMMON_DATA_SERVICE_PORT}
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_URL=http://search-suggestion-service:${SEARCH_SUGGESTION_SERVICE_PORT}
      - REACT_APP_PAYMENT_SERVICE_URL=http://payment-service:${PAYMENT_SERVICE_PORT}
      - REACT_APP_AUTHENTICATION_SERVICE_PORT=${AUTHENTICATION_SERVICE_PORT}
      - REACT_APP_COMMON_DATA_SERVICE_PORT=${COMMON_DATA_SERVICE_PORT}
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT=${SEARCH_SUGGESTION_SERVICE_PORT}
      - REACT_APP_PAYMENT_SERVICE_PORT=${PAYMENT_SERVICE_PORT}
    depends_on:
      - authentication-service
      - common-data-service
      - search-suggestion-service
      - payment-service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
