INSERT INTO search_suggestion (keyword, is_default, search_count) VALUES

('t-shirt', TRUE, 100),
('jeans', TRUE, 95),
('dress', TRUE, 90),
('sweater', TRUE, 85),
('jacket', TRUE, 80),
('shoes', TRUE, 78),
('skirt', TRUE, 75),
('hoodie', TRUE, 73),
('shorts', TRUE, 70),
('pants', TRUE, 68),

-- Category
('summer dress', FALSE, 65),
('winter coat', FALSE, 63),
('casual shirt', FALSE, 60),
('formal shirt', FALSE, 58),
('running shoes', FALSE, 55),
('leather jacket', FALSE, 53),
('denim jacket', FALSE, 50),
('sweatpants', FALSE, 48),
('cardigan', FALSE, 45),
('blouse', FALSE, 43),

-- Accessories
('hat', FALSE, 40),
('scarf', FALSE, 38),
('belt', FALSE, 36),
('sunglasses', FALSE, 35),
('watch', FALSE, 33),
('handbag', FALSE, 32),
('backpack', FALSE, 30),
('socks', FALSE, 28),
('gloves', FALSE, 25),
('jewelry', FALSE, 23),

-- Underwear and night
('underwear', FALSE, 21),
('bra', FALSE, 20),
('lingerie', FALSE, 19),
('pajamas', FALSE, 18),
('bathrobe', FALSE, 17),
('boxers', FALSE, 16),
('briefs', FALSE, 15),
('nightgown', FALSE, 14),
('sleepwear', FALSE, 13),

-- Shoes
('sneakers', FALSE, 48),
('boots', FALSE, 46),
('high heels', FALSE, 44),
('sandals', FALSE, 42),
('loafers', FALSE, 40),
('flip flops', FALSE, 38),
('slippers', FALSE, 36),
('oxford shoes', FALSE, 32),
('ankle boots', FALSE, 30),

-- Sportswear
('sportswear', FALSE, 41),
('leggings', FALSE, 40),
('yoga pants', FALSE, 39),
('sports bra', FALSE, 37),
('gym shorts', FALSE, 35),
('athletic shirt', FALSE, 33),
('tracksuit', FALSE, 31),
('swimming suit', FALSE, 27),
('bikini', FALSE, 25),
('swim trunks', FALSE, 22),

-- Seasons and occasions
('summer collection', FALSE, 38),
('winter collection', FALSE, 36),
('spring fashion', FALSE, 34),
('autumn fashion', FALSE, 32),
('wedding dress', FALSE, 30),
('cocktail dress', FALSE, 28),
('party outfit', FALSE, 26),
('business casual', FALSE, 24),
('formal wear', FALSE, 22),
('maternity clothes', FALSE, 20),

-- Materials and styles
('cotton', FALSE, 26),
('linen', FALSE, 24),
('silk', FALSE, 22),
('wool', FALSE, 20),
('leather', FALSE, 18),
('denim', FALSE, 16),
('polyester', FALSE, 14),
('vintage', FALSE, 12),
('plus size', FALSE, 10),
('sustainable fashion', FALSE, 8);
